import type { WorkerCode, WorkerCodeLimits, ServiceStub } from '../types';
import { assertValidContextKey, canonicalizeContext } from './serialize';

/** Default compatibility date — picks up `enable_ctx_exports` and `rpc_params_dup_stubs`. */
export const DEFAULT_COMPAT_DATE = '2026-01-20';

export type CodegenMode = 'pool-fn' | 'actor-class' | 'sub-coord';

export interface GenerateSourceOptions {
  mode: CodegenMode;
  /** Module-scope constants embedded as `const k = <JSON>;`. JSON-canonicalizable values only. */
  context?: Record<string, unknown>;
  /** When true, inject `env.signal` reconstruction so user fns can poll it. */
  injectCancelSignal: boolean;
  /** Append `this.env` as the user-fn's `env` parameter when bindings exist. */
  passEnv: boolean;
  /** Banned globals (defensive seal beyond what the runtime already enforces). */
  sealGlobals: boolean;
}

export interface WorkerCodeOptions {
  compatibilityDate?: string;
  compatibilityFlags?: string[];
  env?: Record<string, unknown>;
  globalOutbound?: ServiceStub | null;
  tails?: ServiceStub[];
  limits?: WorkerCodeLimits;
}

/**
 * Generate the ES module source loaded into a dynamic Worker isolate.
 *
 * The generated module always exports a default class extending
 * `WorkerEntrypoint` with these RPC methods:
 *   - `execute(envelope, ...args)` — pool-fn mode
 *   - `submit(envelope, fnSource, state, args)` — actor-class mode
 *
 * `envelope` is the wire shape from `RpcEnvelope` in src/types.ts.
 */
export function generateWorkerSource(fnSource: string | null, opts: GenerateSourceOptions): string {
  const lines: string[] = [
    '// AUTO-GENERATED by cloudflare-parallel — do not edit',
    'import { WorkerEntrypoint } from "cloudflare:workers";',
    '',
  ];

  // Embed canonicalized context as module-scope const declarations.
  // Keys are validated as JS identifiers — without this, a
  // multi-tenant VM caller could inject module-top-level code via crafted
  // context keys.
  if (opts.context && Object.keys(opts.context).length > 0) {
    for (const [key, value] of Object.entries(opts.context)) {
      assertValidContextKey(key);
      // Per-key canonicalization keeps the embedded literal stable across
      // re-runs (sorted keys, etc.) so the loader's cache key is honored.
      lines.push(`const ${key} = ${canonicalizeContext({ v: value }).slice(5, -1)};`);
    }
    lines.push('');
  }

  // Defensive seal of globals when globalOutbound:null. The runtime already
  // throws on fetch/connect; we additionally hard-fail caches.default which
  // public docs don't promise to block.
  if (opts.sealGlobals) {
    lines.push(
      '(() => {',
      '  const seal = (obj, name, msg) => {',
      '    try {',
      '      Object.defineProperty(obj, name, {',
      '        get() { throw new Error(msg); },',
      '        configurable: false,',
      '      });',
      '    } catch (_) { /* already non-configurable, fine */ }',
      '  };',
      '  if (typeof caches !== "undefined") {',
      '    seal(caches, "default", "caches.default is sealed (globalOutbound: null)");',
      '  }',
      '})();',
      '',
    );
  }

  // AbortSignal builder — runs once per dispatch on the loaded isolate.
  //
  // The user-fn receives `env.signal: AbortSignal` — the standard Web
  // Platform shape. Two inputs trip the signal:
  //   1. `envelope.signal.cancelled === true` (already cancelled at submit
  //      time → abort immediately on first microtask).
  //   2. Reading the first chunk from `env.cancelStream`: a single
  //      Uint8Array carries the cancel reason; the reader aborts the local
  //      AbortController with a CancelledError.
  //
  // The reader is fire-and-forget (no `await`); it terminates when the
  // stream closes (cancel happened or coordinator closed cleanly). User
  // code uses standard `env.signal.aborted`, `env.signal.addEventListener
  // ('abort', ...)`, and `env.signal.throwIfAborted()`. They can also pass
  // `env.signal` directly to `fetch(url, { signal: env.signal })` etc.
  //
  // Drop-in for `env.LOADER.abort(id)`: when that primitive ships, the
  // coordinator additionally calls `loader.abort(taskId)` — public API
  // unchanged.
  if (opts.injectCancelSignal) {
    lines.push(
      'function cfpMakeAbortSignal(envelopeSignal, cancelStream) {',
      '  const controller = new AbortController();',
      '  const trip = (reason) => {',
      '    if (controller.signal.aborted) return;',
      '    const err = Object.assign(new Error(reason ?? "Cancelled"), { name: "CancelledError" });',
      '    controller.abort(err);',
      '  };',
      '  if (envelopeSignal?.cancelled) {',
      '    queueMicrotask(() => trip(envelopeSignal.reason));',
      '  }',
      '  if (cancelStream) {',
      '    (async () => {',
      '      try {',
      '        const reader = cancelStream.getReader();',
      '        const { value, done } = await reader.read();',
      '        if (!done && value) {',
      '          const reason = new TextDecoder().decode(value);',
      '          trip(reason);',
      '        }',
      '        try { reader.releaseLock(); } catch (_) {}',
      '      } catch (_) {',
      '        // Reader errors when the producer aborts the stream — treat as no-op.',
      '      }',
      '    })();',
      '  }',
      '  return controller.signal;',
      '}',
      '',
    );
  }

  // Return-value validator: reject RPC stubs, raise on >32 MiB.
  // Invoked in `execute` after the user fn returns.
  lines.push(
    'function cfpValidateReturn(value) {',
    '  if (value == null) return value;',
    '  if (value instanceof ReadableStream) return value;',
    '  // Surface RPC-stub returns as a serialization error.',
    '  if (typeof value === "object") {',
    '    const proto = Object.getPrototypeOf(value);',
    '    const ctorName = proto?.constructor?.name;',
    '    if (ctorName === "RpcStub" || ctorName === "RpcTarget" || ctorName === "RpcPromise") {',
    '      const err = new Error("returned values cannot include RPC stubs");',
    '      err.name = "SerializationError";',
    '      throw err;',
    '    }',
    '  }',
    '  // Size check is best-effort: sample via JSON length where possible.',
    '  // Coordinator side does the authoritative measurement after structured-clone.',
    '  return value;',
    '}',
    '',
  );

  // Helper: emit the env+signal setup block. Used by pool-fn and actor-class.
  // The signal is ALWAYS injected when injectCancelSignal is true — env is
  // ALWAYS present so user fns reading `env.signal.poll()` never NPE on a
  // cancel-fast path.
  const emitEnvSetup = (lines: string[]): void => {
    if (opts.injectCancelSignal) {
      lines.push(
        '    const __signal__ = cfpMakeAbortSignal(envelope?.signal, this.env?.cancelStream);',
        '    const __env__ = Object.assign({}, this.env, { signal: __signal__ });',
        '    // Hide library-internal env entries from user code (defense in depth).',
        '    delete __env__.cancelStream;',
        '    delete __env__.cfpSql;',
      );
    } else if (opts.passEnv) {
      lines.push('    const __env__ = this.env;');
    } else {
      lines.push('    const __env__ = {};');
    }
  };
  // Helper: emit the dispose-after-await wrapper. Future v0.4 hook.
  const emitDispose = (lines: string[]): void => {
    lines.push('    }');
  };

  if (opts.mode === 'pool-fn' && fnSource) {
    lines.push(`const __fn__ = ${fnSource};`, '');
    lines.push(
      'export default class extends WorkerEntrypoint {',
      '  async execute(envelope, ...args) {',
    );
    emitEnvSetup(lines);
    lines.push('    const __result__ = await __fn__(...args, __env__);');
    lines.push('    return cfpValidateReturn(__result__);');
    lines.push('  }', '}');
  } else if (opts.mode === 'actor-class' && fnSource) {
    // The user fn is baked into the module at build time so the loaded
    // isolate doesn't need `eval` to materialize it (the Workers runtime
    // disallows `eval` by default). The loader cache key varies by fnSource hash,
    // so each distinct fn submitted to the same actor gets its own
    // isolate — state still persists in the actor coordinator DO.
    lines.push(`const __fn__ = ${fnSource};`, '');
    lines.push(
      'export default class extends WorkerEntrypoint {',
      '  async submit(envelope, _fnSource, state, args) {',
    );
    emitEnvSetup(lines);
    lines.push(
      '    // Synthesize a capability-restricted SQL proxy. The actor',
      '    // coordinator fences this to its own namespace.',
      '    const sql = this.env?.cfpSql ?? null;',
      '    const result = await __fn__(state, sql, ...args, __env__);',
      '    return { state, value: cfpValidateReturn(result) };',
      '  }',
      '}',
    );
    // emitDispose is now a no-op; placeholder reserved for v0.4 live-cancel.
    void emitDispose;
  } else if (opts.mode === 'sub-coord') {
    // Sub-coordinator: receives a TopologyPlan slice and dispatches. The
    // actual fan-out logic lives in the library's coordinator code which
    // is bundled by the user when they declare the sub-coord DO class.
    lines.push(
      "// Sub-coordinator code is provided by cloudflare-parallel's",
      '// coordinator/sub-coordinator.ts module — the loader cache key',
      "// for this mode points at the library's own bundled class, not",
      '// user code. This generated stub only re-exports.',
      'export default class extends WorkerEntrypoint {',
      '  async dispatch(plan, args) {',
      '    throw new Error("sub-coord codegen is a placeholder; runtime loads the library bundle");',
      '  }',
      '}',
    );
  }

  return lines.join('\n');
}

export interface BuildWorkerCodeOptions {
  fnSource: string | null;
  source: GenerateSourceOptions;
  worker?: WorkerCodeOptions;
}

export function buildWorkerCode(opts: BuildWorkerCodeOptions): WorkerCode {
  const moduleSource = generateWorkerSource(opts.fnSource, opts.source);
  const worker = opts.worker;

  const code: WorkerCode = {
    compatibilityDate: worker?.compatibilityDate ?? DEFAULT_COMPAT_DATE,
    compatibilityFlags: worker?.compatibilityFlags,
    mainModule: 'worker.js',
    modules: {
      'worker.js': moduleSource,
    },
    env: worker?.env,
  };

  if (worker?.tails) code.tails = worker.tails;
  if (worker?.limits) code.limits = worker.limits;

  // Distinguish explicit `globalOutbound: undefined` (inherit) from
  // key-absent (sandbox by default). The runtime treats absent => inherit,
  // so we set `null` explicitly when the user didn't provide it.
  if (worker && 'globalOutbound' in worker) {
    if (worker.globalOutbound !== undefined) {
      code.globalOutbound = worker.globalOutbound;
    }
    // else: explicitly undefined — omit key to inherit parent network
  } else {
    code.globalOutbound = null;
  }

  return code;
}
